### ISSUE TITLE
Failed job (lint) due to poetry/requests.utils

### ISSUE THREAD

**Issue by tehkillerbee** [tamland/python-tidal#182]
After merging the latest PR, I noticed a failed Job (lint) that appears unrelated to the PR.
```
  File "/home/runner/.local/lib/python3.10/site-packages/poetry/utils/helpers.py", line 17, in <module>
    from requests.utils import atomic_open
ImportError: cannot import name 'atomic_open' from 'requests.utils' (/usr/lib/python3/dist-packages/requests/utils.py)
Error: The process '/home/runner/.local/bin/poetry' failed with exit code 1
```

I think we specifically require python-requests v. 2.28.0. However, this version should also provide atomic_open. So I am not quite sure whats going wrong.
https://github.com/tamland/python-tidal/pull/161

@2e0byo Thoughts?

**Comment by 2e0byo** [comment]
This bug landed at work today as well.  Looks like something has made whatever method `actions-poetry` used to install poetry break. there's a PR to use pipx which will probably fix things, but I've just switched to the installer from upstream.

**Comment by 2e0byo** [comment]
Fixed.

**Comment by tehkillerbee** [comment]
> Fixed.

Thanks, good to see that I did not overlook something after last PR :)
